### ISSUE TITLE
Add support for vhost-user-net

### ISSUE THREAD

**Issue by sboeuf** [intel/cloud-hypervisor#8]
In order to let users of cloud-hypervisor plug their own network backend, the VMM should support `vhost-user-net` daemons through a global `vhost-user-net` device.

**Comment by sboeuf** [comment]
Subtask from #7

**Comment by bjzhjing** [comment]
Here is a high-level design picture shows how vhost-user-net will work with DPDK + OVS.
![vhost-user-net](https://user-images.githubusercontent.com/46661806/59844669-0df04500-938e-11e9-9060-d8b815ed454f.jpg)

**Comment by sameo** [comment]
@bjzhjing @rbradford 
> Here is a high-level design picture shows how vhost-user-net will work with DPDK + OVS.

Although this is a correct design, and likely one to be used in several production environments, we need something simpler for our default cloud-hypevisor networking setup and testing environment.

The current virtio implementation relies on a TAP interface for sending and receiving packets to and from the kernel. This is currently implemented in the virtio-net device itself. For example, when the guest tries to send a networking packet through its virtio networking interface, the virtio-net device reads it from the virtio Tx queue and then writes it to the TAP interface.

When merging our vhost-user-net implementation we want to do 2 things:

1. Switch our default virtio device implementation to be vhost-user based (a.k.a. vhost-user-net). The virtio-net device implementation won't be the default one anymore.

2. Have our virtio device implementation talk through the vhost-user socket to a TAP based backend, which is different from the ovs+dpdk setup you're describing here. The TAP based backend will be a separate process, and there will be one TAP based vhost-user-net backend process per networking device per guest. For example, if we launch a cloud-hypervisor guest with 2 virtio networking interfaces, we will end up launching 2 vhost-user-net backend processes for that particular guest, each of those processes will handle its own TAP interface. It is up to the host admin to decide what to do with those TAP interfaces: They could be bridged together or not, but this is outside of cloud-hypervisor's scope.

For 2, we *could* re-use some existing implementation (Like the QEMU test one), but we prefer to implement our own backend, in Rust. One of the reason we are switching from a virtio-net implementation to a vhost-user-net one is security. Offloading virtio to a C backend would defeat that purpose, which is why we believe it makes sense to implement our backends in Rust.

**Comment by sboeuf** [comment]
@sameo 
> 1. Switch our default virtio device implementation to be vhost-user based (a.k.a. vhost-user-net). The virtio-net device implementation won't be the default one anymore.

I have one concern, this assumes the user will have to run the `vhost-user` daemon to be able to run the default configuration, which is not ideal.
And I don't think having our VMM spawning the daemon is a good idea since some daemons might require to be run as root while our VMM don't need those privileges.

>One of the reason we are switching from a virtio-net implementation to a vhost-user-net one is security.

I don't think that's true in the case of our `virtio-net` implementation since it is purely handled in userspace. Since we're not pulling `vhost-net` in our case, we don't expose the host kernel to a potential attack from the guest. So really, what `vhost-user-net` can bring in this case is more performance, depending on the way the daemon is implemented, and more flexibility, as anybody could plug its own backend, depending on its needs.

**Comment by sameo** [comment]
> So really, what vhost-user-net can bring in this case is more performance, depending on the way the daemon is implemented, and more flexibility, as anybody could plug its own backend, depending on its needs.

That's correct, yes.
But the more we offload the device implementations, the less privileged the VMM process can become. Ideally, it should only need to be on the KVM group and that's it. Right now since we support virtio-net, the cloud-hypervisor binary needs NET_ADMIN. We would remove that when offloading to vhost-user-net. And only the vhost-user-net backend would need this cap. That's what we gain security wise with this approach.

**Comment by sboeuf** [comment]
>Right now since we support virtio-net, the cloud-hypervisor binary needs NET_ADMIN

Oh I see but that's because we decided to have the default `--net` creating the TAP if not provided. The real case should be the user creating the TAP and providing it. This means the `virtio-net` implementation has nothing to do with the needs for special caps.

**Comment by rbradford** [comment]
@sboeuf If we can move work into a separate process then we can use seccomp filters to ensure each process only has access to what it needs. 

Further by always using vhost-user-net (even for the simple case currently provided by --net) we can remove the virtio-net code. Likewise for block.

**Comment by sboeuf** [comment]
>If we can move work into a separate process then we can use seccomp filters to ensure each process only has access to what it needs.

So you're thinking cloud-hypervisor process would spawn all the daemons along with the actual VMM process, right?

>Further by always using vhost-user-net (even for the simple case currently provided by --net) we can remove the virtio-net code. Likewise for block.

That's true and pretty nice if we can reach this state. But I expect the virtio-net and virtio-blk code should be compiled out with some Rust feature, right?

**Comment by sameo** [comment]
> That's true and pretty nice if we can reach this state. But I expect the virtio-net and virtio-blk code should be compiled out with some Rust feature, right?

There's an obvious difference between shipping a binary with virtio-net and virtio-blk disabled and something more dynamic where *only* if you don't add `--net` to your command line, the VMM binary  runs without virtio networking.

**Comment by bjzhjing** [comment]
@sameo @rbradford @sboeuf @chao-p @yangzhon

Regarding the proposal Samule wrote down, it could bring security benefit by workload offload. However, I guess there will be no performance improvement since we use Tap backend.

For Tap backend, vhost-net could obain better performance. But, as talked with Chao, vhost-net is a good solution to improve performance, but not a good choice regarding security since device is handled in host kernel. Thus, vhost-net with Tap backend solution will not be used in cloud-hypervisor if we consider security with a higher priority.

If not consider vhost-net solution, just to implement the proposal above, that has a separate process running Tap backend to connect vhost-user-device in cloud-hypervisor, data from TX and RX will be handled in the process, virtqueues maintaince and memory mmap will be handled in backend also. Process will has data transaction with host kernel then. vhost-user-net connect OVS+DPDK backend could improve performance since OVS has physical network card passthrough to it. But I 
do not see performance improvement in our case.

It depends on which one we would like to obtain better, security or performance? If security is with a higher priority, we could just go ahead to add Tap backend in another process. If performance is more important for us, I don't think it's necessary to add such Tap vhost-user backend.

Feel free to correct me if anything mentioned above is wrong :-P

**Comment by rbradford** [comment]
@bjzhjing Security takes priority over performance. The design of vhost-user-net should support both:

a.) a TAP backend by default (with similar performance as virtio-net)
b.) The ability for advanced users to switch to something else, i.e. OVS+DPDK

**Comment by rbradford** [comment]
TAP w/ vhost-net is out-of-scope for cloud-hypervisor.

**Comment by bjzhjing** [comment]
@rbradford yes, while has vhost-user-net as default, it brings similar performance like virtio-net while backend is Tap, but will gain performance improvement while OVS+DPDK as backend.
